Future/symbol
ymuichiro/symbol-universal-wallet pull request #3
Opened 2023-07-17 10:45 UTC by 0x070696E65

2023-07-17 15:35 UTC, ymuichiro commented on apps/next/pages/api/transactions/transfer.ts
> +    } catch (err: any) {
この try catch になりますが、ちゃんと呼び出し元で try catch しているのでここではなくとも大丈夫です
（今回は修正不要で、以降は try/catch 不要ということで

@0x070696E65 

```
export default async function create(req: NextApiRequest, res: NextApiResponse) {
    try {
        if (req.method === 'GET') {
            return await getHandle(req, res);
Expand All
	@@ -14,18 +12,18 @@ export default async function create(req/*: NextApiRequest*/, res/*: NextApiResp
        return res.status(500).end();
    }
}
```

2023-07-17 15:42 UTC, ymuichiro commented on packages/symbol/src/services/TransactionService.ts
> +      const transaction = await transactionRoutesApi.getUnconfirmedTransactionRaw({ transactionId: transactionId })
後々バグになる可能性ありなのでこれは修正お願いします。

修正前
```ts
await transactionRoutesApi.getUnconfirmedTransactionRaw({
```

修正後
```ts
await transactionRoutesApi.getUnconfirmedTransaction({transactionId: transactionId})
```

Raw をつけてしまっていますが、これだと Content-Type とか正しく指定されなかったケースに当たった事があって、Raw はよっぽど理由がなければ使わない方が良いと思います

2023-07-17 15:42 UTC, ymuichiro commented on packages/symbol/src/services/TransactionService.ts
> +      const transaction = await transactionRoutesApi.getPartialTransactionRaw({ transactionId: transactionId })
同じく Raw ありパターン発見

2023-07-17 15:43 UTC, ymuichiro commented on packages/symbol/src/services/TransactionService.ts
> +      const transactions = await transactionRoutesApi.searchUnconfirmedTransactionsRaw(searchConfirmedTransactionsRequest)
ここまでみてきて気がついたけど 未加工の json にしないと何かトラブルが発生する？（Raw の話

2023-07-17 15:46 UTC, ymuichiro commented on packages/symbol/src/utils/utils.ts
>      .join('&');
修正しなくともどちらでも良いのですが、こんな丁寧にクエリ連結、url encoding しなくとも、このクラス使えば勝手にやってくれますよ。（encoding 漏れでサイバー攻撃くらうケースもあるので、セキュリティ的にもこっち使った方が安全です）

https://developer.mozilla.org/ja/docs/Web/API/URL#%E4%BD%BF%E7%94%A8%E4%B8%8A%E3%81%AE%E6%B3%A8%E6%84%8F

2023-07-17 15:47 UTC, ymuichiro requested changes
幾つか修正点、確認事項があり、一旦差し戻します！

2023-07-17 16:34 UTC, 0x070696E65 commented on apps/next/pages/api/transactions/transfer.ts
> +    } catch (err: any) {
了解です！
今回も削除しときます

2023-07-17 16:37 UTC, 0x070696E65 commented on packages/symbol/src/utils/utils.ts
>      .join('&');
なるほど！
ここでは以下のようにエンコードせず
```
export function buildQueryString(obj: any): string {
  const queryString = Object.keys(obj)
    .map((key) => {
      const value = obj[key];

      if (value === undefined || value === null || value === '') {
        return '';
      }

      if (Array.isArray(value)) {
        return value
          .map((item: any) =>
            Object.keys(item)
              .map(
                (itemKey) =>
                  `${key}[${itemKey}]=${item[itemKey]}`
              )
              .join('&')
          )
          .join('&');
      } else {
        return `${key}=${value}`;
      }
    })
    .filter((param) => param !== '') // 空のパラメータを除外
    .join('&');
  return queryString;
}
```

使う場所でURLクラス使います！

```
const queryString = buildQueryString(transferTransaction);
const url = new URL(`${BACKEND}/api/transactions/transfer?${queryString}`);
const result = await getDataFromApi(url.toString());
```

という考え方であってますか？

2023-07-17 16:41 UTC, 0x070696E65 commented on packages/symbol/src/services/TransactionService.ts
> +      const transactions = await transactionRoutesApi.searchUnconfirmedTransactionsRaw(searchConfirmedTransactionsRequest)
> 未加工の json にしないと何かトラブルが発生する？
というのがちょっと分かってないんですが
実は以下のようにするとエラーが出るんです
```
return await transactionRoutesApi.getConfirmedTransaction({ transactionId: transactionId })
```

```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'map')

Source
../packages/symbol-rest/dist/models/TransactionInfoDTOTransaction.ts (837:62) @ map

  835 | 'endEpoch': json['endEpoch'],
  836 | 'transactionsHash': json['transactionsHash'],
> 837 | 'cosignatures': ((json['cosignatures'] as Array<any>).map(CosignatureDTOFromJSON)),
      |                                                      ^
  838 | 'transactions': ((json['transactions'] as Array<any>).map(EmbeddedTransactionInfoDTOFromJSON)),
  839 | 'mosaicId': json['mosaicId'],
  840 | 'amount': json['amount'],
```

で、ちょっと分からなくてRawにしちゃったという、、、
内部的にはRawまではエラー出てなくて
```
    async announceTransaction(requestParameters: AnnounceTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnnounceTransactionInfoDTO> {
        const response = await this.announceTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }
```
ここの
`return await response.value();`が原因っぽく

2023-07-22 07:18 UTC, ymuichiro approved these changes

2023-07-22 07:21 UTC, merged